version: "3"
networks:
  api_server_default:
    external: false
services:
  trackle:
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      HTTP_PORT: 3000
      JWT_SECRET: 123123
      JWT_SESSION: "FALSE"
      JWT_EXPIRATION_IN_HOURS: 6
      MONGODB_CONNECTION_STRING: mongo://root:password123@mongo
      MONGODB_DATABASE_NAME: taskle_db
    ports:
      - 3333:3000
