version: "3"
networks:
  api_server_default:
    external: false
services:
  taskle_back-end:
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      HTTP_PORT: ${HTTP_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_SESSION: ${JWT_SESSION}
      JWT_EXPIRATION_IN_HOURS: ${JWT_EXPIRATION_IN_HOURS}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM_MAIL: ${SENDGRID_FROM_MAIL}
      FRONTEND_HTTP_BASE_URL: ${FRONTEND_HTTP_BASE_URL}
    ports:
      - ${HTTP_PORT}:80
